### PR TITLE
Adding methods for getting all virtual, node, rule and pool stats in same request

### PR DESCRIPTION
**Pull request by cgunning**
In my application i need to get stats for all node, pools etc. I found out that you can get all stats in one single request and this brought my execution time to about 1/6 of the time it took before.

### CODE REVIEW

**Comment by pr8kerl** [comment]
@cgunning nice one! I'll be using that. You're good. :)

**Comment by cgunning** [comment]
I'm glad that you like it! I hope it works well with the version you're running. If it doesn't work, it would be nice to know in order to know what my own application supports as well as contributing to your repository in a respectable way :) I really appreciate you accepting my PRs and don't hesitate to tell me if the changes I make are incompatible with the version you're running.

**Comment by pr8kerl** [comment]
@cgunning Hi, I finally got around to playing with stats. I made a couple of changes to your single stats methods which I hope won't break things for you. I have used a LBStatsValue struct instead of LBPoolStatsValue etc and made it a float64. Some of my stat values were huge. But it seems to work on v11. Do you reset your stats regularly?? Am just discovering stats on F5 for myself. Let me know if I've broken anything for you.

**Comment by cgunning** [comment]
Hi @pr8kerl. I'm glad to see that you've been able to play around with my contributions. Thanks for notifying me regarding your changes. I'll check if your changes are compatible with v12 and my code when I get the time. I'll let you know how it goes.

**Comment by cgunning** [comment]
Hi @pr8kerl. Sorry that it's taken such a long time to test the compatibility of your changes with my application. I've now tested it and it seems to work with no problems. I also just realized that you asked me a question regarding if I reset my stats regularly. It may be a bit late but I never reset my stats. Is this something that you need to do with Graphite?

**Comment by pr8kerl** [comment]
Hi @cgunning, No problem at all - thanks for getting back. I am glad to hear that my changes didn't break anything for you. I guess I needn't message you for that - I'm sure you'd let me know if I had caused issues. Was mainly curious. About the stats reset; when  querying our F5 quickly for stats it seemed as though certain stats were simply climbing higher and higher. I haven't started storing stats data yet, so was also curious as to whether the stats counters on an F5 need to be reset daily or hourly when storing their values over time. I should start graphing them all and see for myself. :)
Thanks again for all your help and info. Cheers.

**Pull request merged**
